### ISSUE TITLE
Humanity shows its base value when exporting character sheet as PDF

### ISSUE THREAD

**Issue by hlep** [cybersmily/cybersmily_datafort#24]
**Browser used:**
Firefox

**Area issue occurred:**
Character Generator - CP2020

**To Reproduce**
1. Go to Character Generator - CP2020
2. Add some EMP to the character
3. Add any cyberware with humanity cost to the character
4. Export character sheet as PDF

**Expected behavior**
Humanity number on exported PDF is displayed as `EMP * 10 - the sum of all cyberware HC`

**Screenshots**
![изображение](https://user-images.githubusercontent.com/23423481/96010423-71876700-0e4a-11eb-810a-3ed559c6cbc8.png)
![изображение](https://user-images.githubusercontent.com/23423481/96010491-8237dd00-0e4a-11eb-9d25-ca97c292e3f5.png)

**Additional context**
It counts Humanity correctly on the webpage, but exported PDF shows base humanity value of a character.

**Comment by cybersmily** [comment]
Thanks for spotting this. I will get it fixed for the next release.

**Comment by cybersmily** [comment]
@hlep fix has been pushed
